import path from 'path';
import { PROJECT_ROOT, safeWriteFile, toKebabCase, toPascalCase } from './utils';
import chalk from 'chalk';

interface AppGeneratorOptions {
    name: string; // e.g., "ProjectManager"
}

export const generateApp = async ({ name }: AppGeneratorOptions) => {
    const pascalName = toPascalCase(name);
    const kebabName = toKebabCase(name);

    console.log(chalk.blue(`\nGenerating App: ${pascalName} (${kebabName})...`));

    // 1. App Directory and Components Directory
    const appDir = path.join(PROJECT_ROOT, 'src/apps', kebabName);
    const componentsDir = path.join(appDir, 'components');

    // 2. Main App Component
    const appComponentContent = `
import React from 'react';
import { useOS } from '@/hooks/useOS';

interface ${pascalName}AppProps {
    windowId: string;
}

export default function ${pascalName}App({ windowId }: ${pascalName}AppProps) {
    const { closeWindow } = useOS();

    return (
        <div className="h-full flex flex-col bg-[var(--os-bg)] text-[var(--os-text)]">
            <header className="p-4 border-b border-[var(--os-border)] flex justify-between items-center bg-[var(--os-surface)]">
                <h1 className="text-xl font-bold">${pascalName}</h1>
                <button 
                    onClick={() => closeWindow(windowId)}
                    className="p-1 hover:bg-[var(--os-surface-hover)] rounded"
                >
                    Close
                </button>
            </header>
            <main className="flex-1 p-4 overflow-auto">
                <div className="bg-[var(--os-surface)] p-6 rounded-lg border border-[var(--os-border)] shadow-sm">
                    <p className="text-[var(--os-text-muted)]">
                        Welcome to ${pascalName}! This app was generated by the WebOS CLI.
                    </p>
                    <div className="mt-4">
                        <button className="bg-[var(--os-accent)] text-white px-4 py-2 rounded hover:opacity-90">
                            Get Started
                        </button>
                    </div>
                </div>
            </main>
        </div>
    );
}
`;
    const appComponentPath = path.join(appDir, `${pascalName}App.tsx`);

    // Ensure directories exist recursively via safeWriteFile path logic or manually
    // safeWriteFile handles directory creation.
    safeWriteFile(appComponentPath, appComponentContent.trim());

    // Create empty components dir with a gitkeep or readme
    safeWriteFile(path.join(componentsDir, 'README.md'), `# ${pascalName} Components\n\nPlace app-specific components here.`);

    console.log(chalk.green(`\n✓ App ${pascalName} scaffolded!`));
    console.log(chalk.yellow(`  ⚠ NEXT STEPS:`));
    console.log(`  1. Register the app in 'src/apps/registry.tsx'`);
    console.log(`     - Import: import ${pascalName}App from './${kebabName}/${pascalName}App';`);
    console.log(`     - Add key '${kebabName}' to APP_REGISTRY`);
};
