import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    address: '1240 Highland Ave',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90038',
    price: 850000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    image: 'https://picsum.photos/800/600?random=1',
    type: 'Single Family',
    status: 'PUBLISHED',
    tags: ['Fixer', 'Vacant'],
    metrics: {
      arv: 1200000,
      estRent: 5500,
      capRate: 6.2,
      projectedRoi: 18.5,
      rehabEst: 150000,
    },
    description: 'Prime value-add opportunity in the heart of Hollywood Media District. This craftsman bungalow features original details but needs a full cosmetic rehab. Perfect for BRRRR strategy or fix-and-flip.',
    yearBuilt: 1924,
    location: { lat: 34.093, lng: -118.342 },
    images: ['https://picsum.photos/800/600?random=1', 'https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12'],
  },
  {
    id: '2',
    address: '4502 Eagle Rock Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90041',
    price: 1350000,
    beds: 6,
    baths: 4,
    sqft: 2800,
    image: 'https://picsum.photos/800/600?random=2',
    type: 'Multi Family',
    status: 'PUBLISHED',
    biddingEnabled: true,
    biddingEndDate: new Date(Date.now() + 86400000 * 3).toISOString(), // 3 days from now
    currentBid: 1375000,
    tags: ['Tenant Occupied', 'Cash Flow'],
    metrics: {
      arv: 1500000,
      estRent: 8200,
      capRate: 5.8,
      projectedRoi: 12.0,
      rehabEst: 50000,
    },
    description: 'Solid duplex in Glassell Park. Both units are 3bd/2ba. Front unit vacant, rear unit occupied by long-term tenants. Minor updates needed to maximize rent roll.',
    yearBuilt: 1965,
    location: { lat: 34.125, lng: -118.225 },
    images: ['https://picsum.photos/800/600?random=2', 'https://picsum.photos/800/600?random=21'],
  },
  {
    id: '3',
    address: '789 Pine St',
    city: 'Pasadena',
    state: 'CA',
    zip: '91101',
    price: 925000,
    beds: 2,
    baths: 1.5,
    sqft: 1200,
    image: 'https://picsum.photos/800/600?random=3',
    type: 'Single Family',
    status: 'OFFER_ACCEPTED',
    tags: ['Wholesale', 'Fire Damage'],
    metrics: {
      arv: 1400000,
      estRent: 4800,
      capRate: 0,
      projectedRoi: 25.0,
      rehabEst: 250000,
    },
    description: 'Heavy fixer/tear-down opportunity in prime Pasadena. Fire damage in kitchen and living area. Cash buyers only. Huge upside potential for experienced developers.',
    yearBuilt: 1940,
    location: { lat: 34.147, lng: -118.144 },
    images: ['https://picsum.photos/800/600?random=3', 'https://picsum.photos/800/600?random=31'],
  },
  {
    id: '4',
    address: '2201 Ocean Front Walk',
    city: 'Venice',
    state: 'CA',
    zip: '90291',
    price: 3200000,
    beds: 4,
    baths: 3,
    sqft: 3100,
    image: 'https://picsum.photos/800/600?random=4',
    type: 'Single Family',
    status: 'UNDER_CONTRACT',
    tags: ['Luxury', 'Vacant'],
    metrics: {
      arv: 4100000,
      estRent: 15000,
      capRate: 4.5,
      projectedRoi: 15.2,
      rehabEst: 400000,
    },
    description: 'Rare oceanfront opportunity. Structurally sound but dated interior. Convert to high-end modern masterpiece. Roof deck potential with panoramic views.',
    yearBuilt: 1978,
    location: { lat: 33.985, lng: -118.47 },
    images: ['https://picsum.photos/800/600?random=4', 'https://picsum.photos/800/600?random=41'],
  },
  {
    id: '5',
    address: '550 S Main St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90013',
    price: 650000,
    beds: 1,
    baths: 1,
    sqft: 950,
    image: 'https://picsum.photos/800/600?random=5',
    type: 'Commercial',
    status: 'PUBLISHED',
    tags: ['Rental', 'Turnkey'],
    metrics: {
      arv: 680000,
      estRent: 3200,
      capRate: 5.1,
      projectedRoi: 8.5,
      rehabEst: 5000,
    },
    description: 'Modern loft in the historic core. High ceilings, polished concrete floors. Mills Act approved (low property taxes). Great Airbnb potential or long-term executive rental.',
    yearBuilt: 1910,
    location: { lat: 34.045, lng: -118.245 },
    images: ['https://picsum.photos/800/600?random=5'],
  },
  {
    id: '6',
    address: '8801 Sunset Blvd',
    city: 'West Hollywood',
    state: 'CA',
    zip: '90069',
    price: 2100000,
    beds: 3,
    baths: 3,
    sqft: 2200,
    image: 'https://picsum.photos/800/600?random=6',
    type: 'Single Family',
    status: 'CLOSED',
    tags: ['Value Add'],
    metrics: {
      arv: 2800000,
      estRent: 11000,
      capRate: 4.8,
      projectedRoi: 14.0,
      rehabEst: 200000,
    },
    description: 'Mid-century post-and-beam in the hills. Needs system upgrades and finish modernization. Pool needs resurfacing.',
    yearBuilt: 1958,
    location: { lat: 34.09, lng: -118.38 },
    images: ['https://picsum.photos/800/600?random=6'],
  },
  {
    id: '7',
    address: '3000 E Cesar E Chavez Ave',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90033',
    price: 750000,
    beds: 2,
    baths: 1,
    sqft: 1100,
    image: 'https://picsum.photos/800/600?random=7',
    type: 'Single Family',
    status: 'PUBLISHED',
    tags: ['Network Deal', 'Fixer'],
    metrics: {
      arv: 950000,
      estRent: 4000,
      capRate: 5.5,
      projectedRoi: 16.0,
      rehabEst: 80000,
    },
    description: 'Classic Boyle Heights fixer. Great bones, large lot. Zoned LARD1.5, potential for ADU or additional units. Shared from Equity Homes Network.',
    yearBuilt: 1920,
    location: { lat: 34.048, lng: -118.205 },
    images: ['https://picsum.photos/800/600?random=7'],
    isNetworkDeal: true,
    originatingOrgName: 'Equity Homes',
  },
];

export const INITIAL_FILTER_STATE = {
  location: '',
  priceMin: 0,
  priceMax: 10000000,
  beds: null,
  baths: null,
  propertyTypes: [],
  tags: [],
  includeNetworkDeals: true,
  sortBy: 'newest' as const,
};
