import { ActivityEvent, Deal, DealStatus, Property, PropertyType, TransactionStep } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    address: '1240 Highland Ave',
    baths: 2,
    beds: 3,
    city: 'Los Angeles',
    description: 'Prime value-add opportunity in the heart of Hollywood Media District. This craftsman bungalow features original details but needs a full cosmetic rehab. Perfect for BRRRR strategy or fix-and-flip.',
    id: '1',
    image: 'https://picsum.photos/800/600?random=1',
    images: ['https://picsum.photos/800/600?random=1', 'https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12'],
    location: { lat: 34.093, lng: -118.342 },
    metrics: {
      arv: 1200000,
      capRate: 6.2,
      estRent: 5500,
      projectedRoi: 18.5,
      rehabEst: 150000,
    },
    price: 850000,
    sqft: 1850,
    state: 'CA',
    status: DealStatus.PUBLISHED,
    tags: ['Fixer', 'Vacant'],
    type: PropertyType.SINGLE_FAMILY,
    yearBuilt: 1924,
    zip: '90038',
  },
  {
    address: '4502 Eagle Rock Blvd',
    baths: 4,
    beds: 6,
    biddingEnabled: true,
    biddingEndDate: new Date(Date.now() + 86400000 * 3).toISOString(), // 3 days from now
    city: 'Los Angeles',
    currentBid: 1375000,
    description: 'Solid duplex in Glassell Park. Both units are 3bd/2ba. Front unit vacant, rear unit occupied by long-term tenants. Minor updates needed to maximize rent roll.',
    id: '2',
    image: 'https://picsum.photos/800/600?random=2',
    images: ['https://picsum.photos/800/600?random=2', 'https://picsum.photos/800/600?random=21'],
    location: { lat: 34.125, lng: -118.225 },
    metrics: {
      arv: 1500000,
      capRate: 5.8,
      estRent: 8200,
      projectedRoi: 12.0,
      rehabEst: 50000,
    },
    price: 1350000,
    sqft: 2800,
    state: 'CA',
    status: DealStatus.PUBLISHED,
    tags: ['Tenant Occupied', 'Cash Flow'],
    type: PropertyType.MULTI_FAMILY,
    yearBuilt: 1965,
    zip: '90041',
  },
  {
    address: '789 Pine St',
    baths: 1.5,
    beds: 2,
    city: 'Pasadena',
    description: 'Heavy fixer/tear-down opportunity in prime Pasadena. Fire damage in kitchen and living area. Cash buyers only. Huge upside potential for experienced developers.',
    id: '3',
    image: 'https://picsum.photos/800/600?random=3',
    images: ['https://picsum.photos/800/600?random=3', 'https://picsum.photos/800/600?random=31'],
    location: { lat: 34.147, lng: -118.144 },
    metrics: {
      arv: 1400000,
      capRate: 0,
      estRent: 4800,
      projectedRoi: 25.0,
      rehabEst: 250000,
    },
    price: 925000,
    sqft: 1200,
    state: 'CA',
    status: DealStatus.OFFER_ACCEPTED,
    tags: ['Wholesale', 'Fire Damage'],
    type: PropertyType.SINGLE_FAMILY,
    yearBuilt: 1940,
    zip: '91101',
  },
  {
    address: '2201 Ocean Front Walk',
    baths: 3,
    beds: 4,
    city: 'Venice',
    description: 'Rare oceanfront opportunity. Structurally sound but dated interior. Convert to high-end modern masterpiece. Roof deck potential with panoramic views.',
    id: '4',
    image: 'https://picsum.photos/800/600?random=4',
    images: ['https://picsum.photos/800/600?random=4', 'https://picsum.photos/800/600?random=41'],
    location: { lat: 33.985, lng: -118.47 },
    metrics: {
      arv: 4100000,
      capRate: 4.5,
      estRent: 15000,
      projectedRoi: 15.2,
      rehabEst: 400000,
    },
    price: 3200000,
    sqft: 3100,
    state: 'CA',
    status: DealStatus.UNDER_CONTRACT,
    tags: ['Luxury', 'Vacant'],
    type: PropertyType.SINGLE_FAMILY,
    yearBuilt: 1978,
    zip: '90291',
  },
  {
    address: '550 S Main St',
    baths: 1,
    beds: 1,
    city: 'Los Angeles',
    description: 'Modern loft in the historic core. High ceilings, polished concrete floors. Mills Act approved (low property taxes). Great Airbnb potential or long-term executive rental.',
    id: '5',
    image: 'https://picsum.photos/800/600?random=5',
    images: ['https://picsum.photos/800/600?random=5'],
    location: { lat: 34.045, lng: -118.245 },
    metrics: {
      arv: 680000,
      capRate: 5.1,
      estRent: 3200,
      projectedRoi: 8.5,
      rehabEst: 5000,
    },
    price: 650000,
    sqft: 950,
    state: 'CA',
    status: DealStatus.PUBLISHED,
    tags: ['Rental', 'Turnkey'],
    type: PropertyType.COMMERCIAL,
    yearBuilt: 1910,
    zip: '90013',
  },
  {
    address: '8801 Sunset Blvd',
    baths: 3,
    beds: 3,
    city: 'West Hollywood',
    description: 'Mid-century post-and-beam in the hills. Needs system upgrades and finish modernization. Pool needs resurfacing.',
    id: '6',
    image: 'https://picsum.photos/800/600?random=6',
    images: ['https://picsum.photos/800/600?random=6'],
    location: { lat: 34.09, lng: -118.38 },
    metrics: {
      arv: 2800000,
      capRate: 4.8,
      estRent: 11000,
      projectedRoi: 14.0,
      rehabEst: 200000,
    },
    price: 2100000,
    sqft: 2200,
    state: 'CA',
    status: DealStatus.CLOSED,
    tags: ['Value Add'],
    type: PropertyType.SINGLE_FAMILY,
    yearBuilt: 1958,
    zip: '90069',
  },
  {
    address: '3000 E Cesar E Chavez Ave',
    baths: 1,
    beds: 2,
    city: 'Los Angeles',
    description: 'Classic Boyle Heights fixer. Great bones, large lot. Zoned LARD1.5, potential for ADU or additional units. Shared from Equity Homes Network.',
    id: '7',
    image: 'https://picsum.photos/800/600?random=7',
    images: ['https://picsum.photos/800/600?random=7'],
    isNetworkDeal: true,
    location: { lat: 34.048, lng: -118.205 },
    metrics: {
      arv: 950000,
      capRate: 5.5,
      estRent: 4000,
      projectedRoi: 16.0,
      rehabEst: 80000,
    },
    originatingOrgName: 'Equity Homes',
    price: 750000,
    sqft: 1100,
    state: 'CA',
    status: DealStatus.PUBLISHED,
    tags: ['Network Deal', 'Fixer'],
    type: PropertyType.SINGLE_FAMILY,
    yearBuilt: 1920,
    zip: '90033',
  },
];

export const INITIAL_FILTER_STATE = {
  baths: null,
  beds: null,
  includeNetworkDeals: true,
  location: '',
  priceMax: 10000000,
  priceMin: 0,
  propertyTypes: [],
  sortBy: 'newest' as const,
  tags: [],
};
