import { entities } from '@/db/entities';
import * as fs from 'fs';
import * as path from 'path';

import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GENERATED_DIR = path.join(__dirname, '../src/generated/zod');

async function generate() {
    if (!fs.existsSync(GENERATED_DIR)) {
        fs.mkdirSync(GENERATED_DIR, { recursive: true });
    }

    const imports: string[] = [
        "import { z } from 'zod';",
        "import { createEntitySchemas } from 'typeorm-zod';",
        "import * as Entities from '../../db/entities';"
    ];
    const exports: string[] = [];

    // Get all exported entity names from the entities array
    // We assume the entities array contains the classes
    const entityNames = entities
        .map(e => e.name)
        .filter(name => !['BaseEntity', 'BaseVersionEntity'].includes(name));

    // Sort for stability
    entityNames.sort();

    entityNames.forEach(name => {
        exports.push(`export const ${name}Schemas = createEntitySchemas(Entities.${name});`);
        exports.push(`export type ${name}Insert = z.infer<typeof ${name}Schemas.create>;`);
        exports.push(`export type ${name}Update = z.infer<typeof ${name}Schemas.update>;`);
        exports.push(`export type ${name}Select = z.infer<typeof ${name}Schemas.full>;`);
    });

    const fileContent = [
        "// This file is auto-generated by scripts/generate-zod-schemas.ts",
        "// Do not edit this file manually",
        "",
        ...imports,
        "",
        ...exports,
        ""
    ].join('\n');

    fs.writeFileSync(path.join(GENERATED_DIR, 'index.ts'), fileContent);
    console.log(`Generated Zod schemas for ${entityNames.length} entities in ${path.join(GENERATED_DIR, 'index.ts')}`);
}

generate().catch(console.error);
